name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # Installs dependencies exactly as specified in package-lock.json

      - name: Build project
        run: npm run build  # Uses project's vite build command

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist  # Ensure dist folder exists after build

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4  # Ensures GitHub Pages is properly set up

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist  # Ensure correct directory structure

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
